[[redirects]]
  from = "/programma-elettorale/cnsu"
  to = ""
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/programma-elettorale/CNSU"
  to = "https://linktr.ee/TitoCNSU"
  status = 200
  force = true # COMMENT: ensure that we always redirect


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


